_wandb:
    value:
        cli_version: 0.23.1
        e:
            lilonkkav6kbhedjb8d0qixzffbh5g7z:
                args:
                    - --data_root
                    - cgcnn_data/matbench_log_kvrh_CountBasedOOD
                    - --checkpoint-dir
                    - checkpoints/meta_train/cgcnn
                    - --backbone
                    - cgcnn
                    - --fold
                    - "1"
                    - --num-models
                    - "3"
                    - --num-outer-steps
                    - "50"
                    - --truncation-steps
                    - "3"
                    - --inner-steps
                    - "5"
                    - --meta-lr
                    - "0.001"
                    - --batch-size
                    - "256"
                codePath: modules/meta_train_cgcnn.py
                codePathLocal: modules/meta_train_cgcnn.py
                cpu_count: 192
                cpu_count_logical: 384
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "453313306624"
                        used: "20766302208"
                email: cjpcool@outlook.com
                executable: /home/grads/jianpengc/miniconda3/envs/data_val/bin/python
                git:
                    commit: 36a04025147aa495af8fa1b13e20a1a15c87040c
                    remote: https://github.com/cjpcool/DuetDA
                gpu: NVIDIA H200 NVL
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200 NVL
                      uuid: GPU-fea55f84-ab6f-8ac8-8655-1eea9316aa48
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200 NVL
                      uuid: GPU-a88d0b0c-70a5-aa81-fe8e-69c4666071dd
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200 NVL
                      uuid: GPU-04149834-f9ef-3ef0-eff4-bd6c0d31a14d
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200 NVL
                      uuid: GPU-a64e9466-33f8-c583-36cc-703fe78ac8bf
                host: zhoulab-2
                memory:
                    total: "1622695882752"
                os: Linux-6.8.0-94-generic-x86_64-with-glibc2.39
                program: /data/home/grads/jianpengc/projects/3d_molecule/DuetDA/DuetDA/modules/meta_train_cgcnn.py
                python: CPython 3.14.2
                root: /data/home/grads/jianpengc/projects/3d_molecule/DuetDA/DuetDA
                startedAt: "2026-02-15T18:16:29.411011Z"
                writerId: lilonkkav6kbhedjb8d0qixzffbh5g7z
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 61
            "4": 3.14.2
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
inner_steps:
    value: 5
meta_lr:
    value: 0.001
num_models:
    value: 3
num_outer_steps:
    value: 50
reinit_frequency:
    value: 100
truncation_steps:
    value: 3
